name: local-sanskrit-ocr
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - anyio=4.2.0=py312h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py312h5eee18b_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=py312h06a4308_0
  - attrs=23.1.0=py312h06a4308_0
  - babel=2.11.0=py312h06a4308_0
  - bash=5.0.018=h14c3975_0
  - bash_kernel=0.9.3=pyh4f82c71_0
  - beautifulsoup4=4.12.2=py312h06a4308_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.6.2=py312h06a4308_0
  - brotli-python=1.0.9=py312h6a678d5_7
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2024.12.31=h06a4308_0
  - certifi=2025.1.31=py312h06a4308_0
  - cffi=1.16.0=py312h5eee18b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py312h06a4308_0
  - comm=0.2.2=pyhd8ed1ab_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py312h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.2=h6a678d5_0
  - flask=3.0.3=py312h06a4308_0
  - flask-sqlalchemy=3.1.1=py312h06a4308_0
  - fontconfig=2.14.1=hef1e5e3_0
  - freetype=2.12.1=h4a9f257_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - greenlet=3.1.1=py312h6a678d5_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=58.2=he6710b0_3
  - idna=3.4=py312h06a4308_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - ipykernel=6.29.3=pyhd33586a_0
  - ipython=8.22.2=pyh707e725_0
  - ipywidgets=8.1.2=py312h06a4308_0
  - itsdangerous=2.2.0=py312h06a4308_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=py312h06a4308_0
  - jpeg=9e=h5eee18b_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py312h06a4308_0
  - jsonschema-specifications=2023.7.1=py312h06a4308_0
  - jupyter=1.0.0=py312h06a4308_9
  - jupyter-lsp=2.2.0=py312h06a4308_0
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_console=6.6.3=py312h06a4308_1
  - jupyter_core=5.5.0=py312h06a4308_0
  - jupyter_events=0.8.0=py312h06a4308_0
  - jupyter_server=2.10.0=py312h06a4308_0
  - jupyter_server_terminals=0.4.4=py312h06a4308_1
  - jupyterlab=4.0.11=py312h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.25.1=py312h06a4308_0
  - jupyterlab_widgets=3.0.10=py312h06a4308_0
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.38=h1181459_1
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libedit=3.1.20230828=h5eee18b_0
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=hc881cc4_6
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=13.2.0=hc881cc4_6
  - libiconv=1.16=h7f8727e_2
  - libllvm14=14.0.6=hdb19cb5_3
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.45.3=h2797004_0
  - libstdcxx-ng=13.2.0=hc0a3c3a_7
  - libuuid=2.38.1=h0b41bf4_0
  - libxcb=1.15=h7f8727e_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libzlib=1.2.13=hd590300_5
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.5=py312h98912ed_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mistune=2.0.4=py312h06a4308_0
  - mysql=5.7.24=h721c034_2
  - nbclient=0.8.0=py312h06a4308_0
  - nbconvert=7.10.0=py312h06a4308_0
  - nbformat=5.9.2=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - notebook=7.0.8=py312h06a4308_0
  - notebook-shim=0.2.3=py312h06a4308_0
  - numpy=1.26.4=py312h2809609_0
  - numpy-base=1.26.4=py312he1a6c75_0
  - openssl=3.2.1=hd590300_1
  - overrides=7.4.0=py312h06a4308_0
  - packaging=24.0=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.42=hebb0a14_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=23.3.1=py312h06a4308_0
  - platformdirs=4.2.1=pyhd8ed1ab_0
  - ply=3.11=py312h06a4308_1
  - prometheus_client=0.14.1=py312h06a4308_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - prompt_toolkit=3.0.42=hd8ed1ab_0
  - psutil=5.9.0=py312h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyqt=5.15.10=py312h6a678d5_0
  - pyqt5-sip=12.13.0=py312h5eee18b_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.2=hab00c5b_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-dotenv=0.21.0=py312h06a4308_0
  - python-fastjsonschema=2.16.2=py312h06a4308_0
  - python-json-logger=2.0.7=py312h06a4308_0
  - python_abi=3.12=4_cp312
  - pytz=2024.1=py312h06a4308_0
  - pyyaml=6.0.1=py312h5eee18b_0
  - pyzmq=25.1.2=py312h6a678d5_0
  - qt-main=5.15.2=h7358343_9
  - qtconsole=5.5.1=py312h06a4308_0
  - qtpy=2.4.1=py312h06a4308_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py312h06a4308_0
  - requests=2.31.0=py312h06a4308_1
  - rfc3339-validator=0.1.4=py312h06a4308_0
  - rfc3986-validator=0.1.1=py312h06a4308_0
  - rpds-py=0.10.6=py312hb02cf49_0
  - scikit-learn=1.5.1=py312h526ad5a_0
  - send2trash=1.8.2=py312h06a4308_0
  - setuptools=68.2.2=py312h06a4308_0
  - sip=6.7.12=py312h6a678d5_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.0=py312h06a4308_0
  - soupsieve=2.5=py312h06a4308_0
  - sqlalchemy=2.0.34=py312h00e1ef3_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - terminado=0.17.1=py312h06a4308_0
  - threadpoolctl=3.5.0=py312he106c6f_0
  - tiktoken=0.7.0=py312h26f7dfd_0
  - tinycss2=1.2.1=py312h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.3.3=py312h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing-extensions=4.11.0=hd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - urllib3=2.1.0=py312h06a4308_1
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webencodings=0.5.1=py312h06a4308_2
  - websocket-client=0.58.0=py312h06a4308_4
  - wheel=0.41.2=py312h06a4308_0
  - widgetsnbextension=4.0.10=py312h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - ansicolors==1.1.8
      - astunparse==1.6.3
      - contourpy==1.2.1
      - cycler==0.12.1
      - easyocr==1.7.1
      - entrypoints==0.4
      - filelock==3.13.4
      - fire==0.6.0
      - flask-cors==5.0.0
      - flatbuffers==24.3.25
      - fonttools==4.51.0
      - frozenlist==1.5.0
      - fsspec==2024.3.1
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.65.1
      - h5py==3.11.0
      - imageio==2.34.1
      - joblib==1.4.0
      - keras==3.4.1
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - libclang==18.1.1
      - lmdb==1.4.1
      - markdown==3.6
      - markdown-it-py==3.0.0
      - matplotlib==3.8.4
      - mdurl==0.1.2
      - ml-dtypes==0.4.0
      - mpmath==1.3.0
      - multidict==6.1.0
      - namex==0.0.8
      - natsort==8.4.0
      - networkx==3.3
      - ninja==1.11.1.1
      - nltk==3.8.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python-headless==4.9.0.80
      - opt-einsum==3.3.0
      - optree==0.12.1
      - pandas==2.2.2
      - papermill==2.6.0
      - pillow==10.3.0
      - propcache==0.2.0
      - protobuf==4.25.3
      - pyclipper==1.3.0.post5
      - pymupdf==1.24.9
      - pymupdfb==1.24.9
      - pyparsing==3.1.2
      - python-bidi==0.4.2
      - regex==2024.4.16
      - rich==13.7.1
      - scikit-image==0.23.2
      - scipy==1.13.0
      - shapely==2.0.4
      - sympy==1.12
      - tenacity==9.0.0
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.17.0
      - termcolor==2.4.0
      - tifffile==2024.4.18
      - torch==2.2.2
      - torchvision==0.17.2
      - tqdm==4.66.2
      - tzdata==2024.1
      - werkzeug==3.0.3
      - wrapt==1.16.0
      - yarl==1.17.1
